name: Backing up notes
on: 
  schedule:
    - cron: 0 */10 * * *
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: ./action-a
      #   with:
      #     MY_NAME: "Soutrik"
      # - run: pip install numpy
#       - run: pip install os
      - run: |
          git config --global user.name ${{ secrets.CI_GITHUB_USERNAME }}
          git config --global user.email ${{ secrets.CI_GITHUB_EMAIL }}
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout master
          ls -la
      - run: python3 automatednotionbackup.py
        env:
          TZ: ${{secrets.TZ}}
          NOTION_TOKEN_V2: ${{secrets.NOTION_TOKEN_V2}}
          NOTION_SPACE_ID : ${{secrets.NOTION_SPACE_ID}}
          EXPORT_FILENAME : ${{secrets.EXPORT_FILENAME}}
          # PYTHONUNBUFFERED : ${{secrets.PYTHONUNBUFFERED}}
      - run: |
          ls -la
          set -e
          mkdir -p backup
          rm -rf backup/* && unzip -q "${{secrets.EXPORT_FILENAME}}" -d backup/
          stats="\$(git diff --shortstat | xargs)"
          if [ -z "\${stats}" ]; then stats=none; fi
          printf "Updated: %s\n\nUpdates: %s" "\$(date)" "\$stats" > README.md
          git add backup README.md && git commit -m "Updates: \$stats"
          git push origin master
#         git push origin HEAD:master
#         git add .
#         git commit -m "Github actions ran"